# StyLua configuration file
# For more configuration options see: https://github.com/JohnnyMorganz/StyLua

# Indentation type and width
indent_type = "Spaces"
indent_width = 2

# Line ending style (Unix, Windows, None)
line_endings = "Unix"

# Quote style (AutoPreferDouble, AutoPreferSingle, ForceDouble, ForceSingle)
quote_style = "AutoPreferDouble"

# Call parentheses style (Always, NoSingleString, NoSingleTable, None)
call_parentheses = "Always"

# Collapse simple statements to one line (Never, ConditionalCollapse, Always)
collapse_simple_statement = "Never"

# Table sorting
sort_requires = { enabled = false }

# Column width limit
column_width = 120

